# Generated by Django 5.2.8 on 2025-11-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0002_budget"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency_symbol", models.CharField(default="$", max_length=10)),
                ("currency_code", models.CharField(default="USD", max_length=10)),
            ],
        ),
    ]
